project:
  type: website
  output-dir: docs

website:
  title: "Diva's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: FYP Project.qmd
        text: FYP Project
      - href: reflection.qmd
        text: Reflection

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left


